// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMpfSz3FyIrJPwmFAAyTolZKRSf_PIHg',
    appId: '1:756049428293:web:574f20a39f684c49c3882c',
    messagingSenderId: '756049428293',
    projectId: 'budget-tracker-24fbf',
    authDomain: 'budget-tracker-24fbf.firebaseapp.com',
    storageBucket: 'budget-tracker-24fbf.firebasestorage.app',
    measurementId: 'G-HFSN8Z4PPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-HL9U1NNYa3HlIJQtuEyWQX5xVSD5Qbc',
    appId: '1:756049428293:android:4994db8c3a4c577bc3882c',
    messagingSenderId: '756049428293',
    projectId: 'budget-tracker-24fbf',
    storageBucket: 'budget-tracker-24fbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_i6L0cajPvdyyZK4DK6EvTx1dDyndPgM',
    appId: '1:756049428293:ios:e93860c176ec961ac3882c',
    messagingSenderId: '756049428293',
    projectId: 'budget-tracker-24fbf',
    storageBucket: 'budget-tracker-24fbf.firebasestorage.app',
    iosBundleId: 'com.parpuha.budgetTracker',
  );
}
